### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by 0323pin** [ahamlinman/xt#1]
Hi,

I've packaged `xt` for NetBSD yesterday and merged the package into our wip (testing) repository. You can find the commit [here](https://mail-index.netbsd.org/pkgsrc-wip-changes/2023/08/01/msg027877.html) 

There's basically nothing stopping the merge into the main branch, except that we already have another package named `xt` 😞
See, https://pkgsrc.se/textproc/xt

Fortunately, this package is not an executable and there won't be a conflict but, we do need a package name.
Do you have a preference? Else, I was thinking `xt-rs`.

Thanks!

**Comment by ahamlinman** [comment]
Hi @0323pin, thanks for reaching out! I have no real preference here, the `xt-rs` suggestion sounds quite reasonable to me.

For what it's worth, this is my first experience having something packaged in a distribution—if there's anything else I can do from my end to help smooth out the process, please let me know and I'd be happy to take it under consideration.

**Comment by 0323pin** [comment]
Thank you. Fixed in https://github.com/ahamlinman/xt/pull/2
